import Head from "next/head";
import AddPokemon from "../components/AddPokemon";
import Header from "../components/layout/Header";
import PokemonList from "../components/PokemonList";
import Search from "../components/Search";

export default function Home() {
	return (
		<div className="w-full flex flex-col items-center">
			<Head>
				<title>fam RunSys Pokemon</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="w-full flex flex-col justify-center items-center max-w-3xl p-2 select-none">
				<Header />
				<Search />
				<AddPokemon />
				<PokemonList />
			</main>
		</div>
	);
}
